# Configuration Example: LLM-Driven Representative Selection
# Updated version that asks LLM to choose the representative

construction:
  semantic_dedup:
    head_dedup:
      enabled: true
      merge_strategy: "alias"  # Use alias method
      
      # NEW: Use LLM to select representative
      use_llm_for_representative_selection: true  # Let LLM decide, not code heuristics
      
      # Alias configuration
      alias_relation_name: "alias_of"
      
      # Semantic deduplication
      enable_semantic: true
      similarity_threshold: 0.85  # For post-filtering (not used in representative selection)
      use_llm_validation: true     # Must be true for LLM-driven representative selection
      max_candidates: 1000
      candidate_similarity_threshold: 0.75

prompts:
  head_dedup:
    # Original prompt (still available for backward compatibility)
    general: |-
      You are an expert in knowledge graph entity resolution.
      TASK: Determine if the following two entities refer to the SAME real-world object.
      ...
      OUTPUT FORMAT (strict JSON):
      {
        "is_coreferent": true/false,
        "rationale": "..."
      }
    
    # NEW: Improved prompt with representative selection
    with_representative_selection: |-
      You are an expert in knowledge graph entity resolution.

      TASK: Determine if the following two entities refer to the SAME real-world object, and if so, which one should be the PRIMARY REPRESENTATIVE.

      Entity 1 (ID: {entity_1_id}): {entity_1_desc}
      Graph relationships:
      {graph_context_1}
      Source text:
      {chunk_context_1}

      Entity 2 (ID: {entity_2_id}): {entity_2_desc}
      Graph relationships:
      {graph_context_2}
      Source text:
      {chunk_context_2}

      CRITICAL RULES:

      1. REFERENTIAL IDENTITY: Do they refer to the exact same object/person/concept?
         - Same entity with different names → YES (e.g., "NYC" = "New York City")
         - Different but related entities → NO (e.g., "Apple Inc." ≠ "Apple Store")

      2. SUBSTITUTION TEST: Can you replace one with the other in all contexts?

      3. CONSERVATIVE PRINCIPLE:
         - When uncertain about coreference → answer NO
         - When uncertain about representative → choose the one with MORE relationships
         - False merge is worse than false split

      CONTEXT USAGE GUIDANCE (MANDATORY):
      
      The provided context (relationships and source text) is additional information to help you determine coreference. Use it wisely:
      
      1. **Identify contradictions**: If the contexts reveal contradictory information about the two entities, they are DIFFERENT entities → answer NO
      
      2. **Find supporting evidence**: If the contexts show consistent and complementary information, it supports the coreference hypothesis
      
      3. **Assess information sufficiency**: If context is too limited to make a confident decision, apply CONSERVATIVE PRINCIPLE → answer NO
      
      4. **Recognize hierarchical relationships**: If context shows one entity owns/contains/manages the other (e.g., company vs subsidiary, organization vs department), they are DIFFERENT entities → answer NO
      
      IMPORTANT: Do NOT verify the context itself - trust it and USE it to make better coreference decisions.

      DECISION PROCEDURE:
      For Entity 1 and Entity 2, follow these steps IN ORDER:
        
        PHASE 1: USE CONTEXT TO INFORM COREFERENCE DECISION
          → Use the provided context (relationships and source text) to identify contradictions or supporting evidence
          → If context reveals contradictions or hierarchical relationships → they are DIFFERENT
          → If context is insufficient → apply conservative principle
        
        PHASE 2: COREFERENCE DETERMINATION
          Step 1: Check if names are variations of the same entity (e.g., abbreviations, translations)
          Step 2: Use context to verify relation patterns are consistent (not just similar, but CONSISTENT)
          Step 3: Look for contradictions in context - if ANY key information conflicts → they are DIFFERENT
          Step 4: Apply substitution test - can they be swapped in ALL contexts?
          Step 5: If uncertain → answer NO (conservative principle)
        
        PHASE 3: REPRESENTATIVE SELECTION (only if coreferent)
          Choose PRIMARY REPRESENTATIVE based on:
            a) **Formality and Completeness**: Full name > Abbreviation, BUT domain conventions matter
            b) **Domain Convention**: Medical/Academic prefer standard terms, Popular prefers common forms
            c) **Information Richness**: Entity with MORE relationships (visible in context above)
            d) **Naming Quality**: Official name > Colloquial, Standard spelling > Variant
            e) **Cultural Context**: Consider primary language and widely recognized forms

      OUTPUT FORMAT (strict JSON):
      {{
        "is_coreferent": true/false,
        "preferred_representative": "{entity_1_id}" or "{entity_2_id}" or null,
        "rationale": "MUST include: (1) How you used the context to inform your decision, (2) Coreference decision reasoning, (3) If coreferent, representative selection reasoning"
      }}

      IMPORTANT NOTES:
      - Set "preferred_representative" ONLY if "is_coreferent" is true
      - If "is_coreferent" is false, set "preferred_representative" to null
      - The "preferred_representative" must be exactly one of: "{entity_1_id}" or "{entity_2_id}"
      - Always include context verification results in rationale to demonstrate thorough analysis

# Example usage in code:
# 
# config.construction.semantic_dedup.head_dedup.use_llm_for_representative_selection = True
# 
# Then call:
# stats = builder.deduplicate_heads_with_llm_v2()
