version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.12-community-ubi9
    container_name: youtu-graphrag-neo4j-ubi9
    restart: unless-stopped
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      # 设置初始密码
      - NEO4J_AUTH=neo4j/graphrag123
      # 内存设置
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # 安全设置
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      # 允许从任何地址连接
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      # 启用 APOC 插件（可选，用于高级图操作）
      - NEO4J_PLUGINS=["apoc"]
      # UBI9 特有设置
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      # 持久化数据
      - neo4j_data_ubi9:/data
      - neo4j_logs_ubi9:/logs
      - neo4j_import_ubi9:/var/lib/neo4j/import
      - neo4j_plugins_ubi9:/plugins
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  neo4j_data_ubi9:
    name: youtu_graphrag_neo4j_data_ubi9
  neo4j_logs_ubi9:
    name: youtu_graphrag_neo4j_logs_ubi9
  neo4j_import_ubi9:
    name: youtu_graphrag_neo4j_import_ubi9
  neo4j_plugins_ubi9:
    name: youtu_graphrag_neo4j_plugins_ubi9

networks:
  default:
    name: youtu-graphrag-network-ubi9